### ISSUE TITLE
Get our cache validation repository listed in GitHub actions marketplace

### ISSUE THREAD

**Issue by edthedev** [techservicesillinois/cache-validation#2]
@edthedev I requested a public repo called cache-validation. IMO It would be nice to also get it listed on the Github Actions Marketplace: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

_Originally posted by @ddriddle in https://github.com/techservicesillinois/awscli-login/issues/75#issuecomment-805160206_

Tasks:
+ [x] ensure a valid license is in place (i.e. U of I / NCSA License, or at least one containing the required no-warranty language)
+ [x] add our support and end-of-life language to the README.
+ [x] ensure the README has enough to help potential implementors
+ [x] update the README as needed to support any automatic documentation features supported by GitHub marketplace.
+ [x] get the repository listed in GitHub actions marketplace

**Comment by ddriddle** [comment]
To publish the repo on the Github Marketplace we need a techservicesillinois admin to agree to the GitHub Marketplace Developer Agreement. I sent a request to the admins today.

**Comment by ddriddle** [comment]
V1.0.0 has been released on Github Actions: https://github.com/marketplace/actions/cache-validation. We may want to customize the branding (See #13)

**Comment by edthedev** [comment]
Working through some unit tests failing during GitHub actions run.
